turkishWords = [
    "abaküs",
    "açı",
    "açının başlangıç kenarı",
    "açının bitiş kenarı",
    "açının bütünleri",
    "açının çizimi",
    "açının derece cinsinden ölçümü",
    "açının dış bölgesi",
    "açının iç bölgesi",
    "açının kenarları",
    "açının köşesi",
    "açının ölçümü",
    "açının tümleri",
    "alçalma açısı",
    "aykırı doğrular arasındaki açı",
    "çevre açı",
    "dar açı",
    "dış açı",
    "dik açı",
    "doğru açı",
    "doğru ile düzlem arasındaki açı",
    "doğrular arasındaki açı",
    "doğrultu açısı",
    "doğrunun eğim açısı",
    "dönme açısı",
    "düzlemler arasındaki açı",
    "eğriler arasındaki açı",
    "geniş açı",
    "ışığın geliş açısı",
    "ışığın kırılma açısı",
    "ışığın yansıma açısı",
    "iç açı",
    "merkez açı",
    "negatif açı",
    "ölçüsü 180'den büyük, 360'tan küçük olan açı",
    "pozitif açı",
    "standard konumdaki açı",
    "taban açısı",
    "tam açı",
    "tepe açısı",
    "vektörler arasındaki açı",
    "yükselme açısı",
    "açı çiftleri",
    "bütünler açılar",
    "dış ters açılar",
    "doğrusal çift",
    "iç ters açılar",
    "karşı durumlu açılar",
    "komşu açılar",
    "komşu bütünler açılar",
    "komşu tümler açılar",
    "ters açılar",
    "tümler açılar",
    "yöndeş açılar",
    "açık",
    "açık aralık",
    "açık cümle",
    "açık disk",
    "açık küre",
    "açık önerme",
    "açık önermenin doğruluk kümesi",
    "açık uçlu",
    "açık yarı düzlem",
    "açık",
    "açık hata",
    "açıklık",
    "çeyrek açıklık",
    "açılım",
    "ondalık açılım",
    "açılmış şekli",
    "açınım",
    "açınımın çizimi",
    "küpün açınımı",
    "üçgen piramidin açınımı",
    "açıortay",
    "dış açıortaylar",
    "iç açıortaylar",
    "açıortaylar arasındaki açılar",
    "açıortay teoremi",
    "karşıt açıortay teoremi",
    "üçgenin açıortaylarının noktadaş olması teoremi",
    "açıölçer",
    "açı ölçüsü birimleri",
    "derece",
    "dakika",
    "radyan",
    "saniye",
    "açısal",
    "açısal hız",
    "açısal frekans",
    "açısal ivme",
    "açısal ölçü",
    "açmak",
    "piramidi açmak",
    "prizmayı açmak",
    "silindirin eğri yüzeyini açmak",
    "adım",
    "adi kesir",
    "adil",
    "adil oyun",
    "hilesiz zar",
    "ağaç dalı diyagramı",
    "ağır",
    "ağırlık",
    "ağırlıklı ortalama",
    "ağırlık merkezi",
    "düzgün dört yüzlünün ağırlık merkezi",
    "üçgenin ağırlık merkezi",
    "akıl yürütme",
    "akım",
    "elektrik akımı",
    "rüzgar akımı",
    "su akıntısı",
    "akış diyagramı",
    "akış diyagramlı ispat",
    "aksi belirtilmedikçe",
    "aksine örnek vererek ispat",
    "aksiyom",
    "alan",
    "düzlemsel şekillerin alanı",
    "prizma veya piramidin taban alanı",
    "prizma veya piramidin yanal alanı",
    "prizma veya piramidin yüzeysel alanı (toplam alanı)",
    "alan denkliği postulatı",
    "alan toplama postulatı",
    "alçalan (azalan) fonksiyon",
    "alçalma açısı",
    "alfa",
    "algoritma",
    "alıcı",
    "alış fiyatı",
    "alt aralık",
    "alt çeyrek",
    "alt determinant",
    "alternatif akım",
    "alterne (dalgalı) seri",
    "altıgen",
    "düzgün altıgen",
    "altıgen prizma",
    "düzgün altıgen prizma",
    "altın dikdörtgen",
    "altın oran",
    "altın üçgen",
    "altı yüzlü",
    "düzgün altı yüzlü",
    "alt kenar",
    "alt küme",
    "alt küme özellikleri",
    "k-elemanlı alt küme",
    "öz alt küme",
    "alt limit",
    "alt matris",
    "alt sınır",
    "en büyük alt sınır",
    "alt taban",
    "alttan sınırlı",
    "alttan sınırlı fonksiyon",
    "alt üçgensel matris",
    "amortisman",
    "ana birimler",
    "ana eksen parçası",
    "yarı ana eksen parçası",
    "ana köşegen",
    "analitik",
    "analitik çözüm",
    "analitik düzlem",
    "analitik fonksiyon",
    "analitik geometri",
    "diferansiyel denklemin analitik çözümü",
    "analitik trigonometri",
    "geometriye analitik yaklaşım",
    "analiz",
    "grafiksel analiz",
    "sayısal analiz",
    "analoji",
    "anapara",
    "ancak ve ancak",
    "ancak ve ancak bağlacı",
    "ani hız",
    "ani ivme",
    "anlam",
    "anlam taşıyan",
    "antilogaritma",
    "apotem",
    "apsis; x-koordinatı",
    "apsisler ekseni",
    "arada olma",
    "ara değerini bulma",
    "ara değerini bulmak",
    "ara değer teoremi",
    "ara değişkenler",
    "arakesit",
    "aralarında asal sayılar",
    "aralığın parçalanması",
    "aralık",
    "açık aralık",
    "aralık notasyonu",
    "kapalı aralık",
    "yakınsaklık aralığı",
    "yarı açık (veya yarı kapalı) aralık",
    "aranjmanlar",
    "arasına sıkıştırmak; eklemek",
    "ard arda",
    "ardışık",
    "ardışık çift sayılar",
    "ardışık olmayan",
    "ardışık tam sayılar",
    "ardışık tek sayılar",
    "Argand diyagramı",
    "argüman",
    "aritmetiğin esas (temel) teoremi",
    "aritmetik",
    "aritmetik dizi",
    "aritmetik dizinin terimleri",
    "ilk n terimin toplamı",
    "n'inci terim; genel terim",
    "aritmetik işlemler",
    "fonksiyonların aritmetik işlemleri",
    "aritmetik ortalama",
    "aritmetik seri",
    "Arşimet cisimleri",
    "Arşimet spirali",
    "artan dizi",
    "artan fonksiyon",
    "mutlak artan fonksiyon",
    "artı",
    "artı veya eksi",
    "artı sembolü",
    "artış hızı",
    "artmak",
    "artma nispeti; artma hızı",
    "artmayan dizi",
    "artmayan fonksiyon",
    "arz",
    "asal",
    "asal bölen",
    "asal çarpanlar",
    "asal çarpanlara ayırma",
    "asal özelliği",
    "asal çember",
    "asimetrik; simetrik olmayan",
    "asimptot",
    "düşey asimptot",
    "eğik asimptot",
    "eğri asimptot",
    "yatay asimptot",
    "asimptot durumunda",
    "aşağıdaki; takip eden",
    "aşağıdaki gibi",
    "aşağı doğru giden; alçalan; azalan",
    "aşağıya doğru",
    "aşikar",
    "aşina",
    "ayırmak",
    "aykırı doğrular",
    "aynı anda meydana gelemeyen olaylar",
    "aynı anda sağlanan lineer denklemler",
    "aynı büyüklükte",
    "aynı merkezli",
    "aynı merkezli küreler",
    "aynı merkezli çemberler",
    "aynı merkezli olmayan",
    "aynı noktadan geçen; noktadaş",
    "aynı noktadan geçmek",
    "aynı noktadan geçen doğrular",
    "ayrık kümeler",
    "ayrık olaylar",
    "ayrıntılar",
    "azalan dizi",
    "azalan fonksiyon",
    "mutlak azalan fonksiyon",
    "azalan seri",
    "azalan sıra",
    "azalma hızı",
    "azalmak",
    "azalmayan dizi",
    "azalmayan fonksiyon"
]

def generate_html(word):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{word}</title>
</head>
<body>
    <h1>{word}</h1>
</body>
</html>
"""

for word in turkishWords:
    html_content = generate_html(word)
    file_name = f"{word}.html"
    # Save the html_content to a file named file_name
    with open(file_name, 'w', encoding='utf-8') as file:
        file.write(html_content)
        # You might need to handle file paths and directories as required
